runmode: debug               # 开发模式, debug, release, test
addr: :6663                  # HTTP绑定端口
name: apiserver              # API Server的名字
url: http://127.0.0.1:6663   # pingServer函数请求的API服务器的ip:port
max_ping_count: 10           # pingServer函数尝试的次数
log:
  writers: file,stdout
  logger_level: log/apiserver.log
db:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: root
  password: 11111111
docker:
  name: db_apiserver
  addr: 127.0.0.1:3306
  username: root
  password: 11111111

logger:
  file:
    path: /opt/logs/apiserver/
    name: log.log